# Generated by Django 4.0.3 on 2022-05-24 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_course_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.FileField(default='test.jpg', upload_to='images'),
            preserve_default=False,
        ),
    ]
