# Generated by Django 4.0.3 on 2022-05-24 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_course_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.FileField(default='andrea-de-santis-zwd435-ewb4-unsplash.jpg', upload_to='images'),
        ),
    ]
